const actionTypes = {
    CHECKED_IF_LOGGED_IN: 'CHECKED_IF_LOGGED_IN',
    SESSION_EXPIRE_REQUESTED: 'SESSION_EXPIRE_REQUESTED',

    USER_DATA: 'USER_DATA',
    HISTORY_FILTER_DROPDOWN: 'HISTORY_FILTER_DROPDOWN',

    AUTH_LOADING_STOPPED: 'AUTH_LOADING_STOPPED',
    AUTH_LOADING_STARTED: 'AUTH_LOADING_STARTED',

    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_SUCCEEDED: 'LOGIN_SUCCEEDED',
    LOGIN_FAILED: 'LOGIN_FAILED',

    COUNTER_CHANGE: 'COUNTER_CHANGE',

    SET_INDEX: 'SET_INDEX',
    COPY_MEDICAL_DATA: 'COPY_MEDICAL_DATA', 
    FORWARD_MEDICAL_DATA: 'FORWARD_MEDICAL_DATA',
    CAN_SET_MEDICAL_PROPS: 'CAN_SET_MEDICAL_PROPS',

    PATIENT_RECORD: 'PATIENT_RECORD',
    CHECKUP_DETAIL: 'CHECKUP_DETAIL',
    MEDICAL_HISTORY_DATA: 'MEDICAL_HISTORY_DATA',
    VITAL: 'VITAL',

    PREVIEW_RECORD: 'PREVIEW_RECORD',
    IS_PREVIEW_DATA_SAVED: 'IS_PREVIEW_DATA_SAVED',
    
    setCourseCategory: 'setCourseCategory'
};

export { actionTypes };
